name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    uses: ./.github/workflows/build_docs.yml
    with:
      artifact_name: twsfwphysx-docs-html

  build-python-docs:
    uses: ./.github/workflows/build_python_binding_docs.yml
    with:
      artifact_name: twsfwphysx-python-docs-html

  deploy:
    needs: [build-docs, build-python-docs]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download HTML doc artifact
        uses: actions/download-artifact@v4
        with:
          name: twsfwphysx-docs-html
          path: docs_build

      - name: Download HTML doc artifact of Python binding
        uses: actions/download-artifact@v4
        with:
          name: twsfwphysx-python-docs-html
          path: docs_build/python-binding

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs_build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
