name: Validation of Python binding

on:
  pull_request:

  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install package
        working-directory: python-binding
        run: |
          pip install -e .[dev]
          pip install ruff

      - name: Run ruff format check
        working-directory: python-binding
        run: ruff format --check

      - name: Run ruff linters
        working-directory: python-binding
        run: ruff check

  tests:
    needs: [ lint ]

    strategy:
      matrix:
        os: [ macos-14, ubuntu-24.04, windows-2022 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install package
        working-directory: python-binding
        run: pip install -e .[dev]

      - name: Run test suite
        working-directory: python-binding
        run: pytest
